Template for adding task
maciejdrobnik/SportManager pull request #26
Opened 2023-04-04 10:50 UTC by maciejdrobnik

I created the template for adding task. In this PR is also the adding the roles and I used it for addTask button which is visible only for team manager.

2023-04-11 13:49 UTC, mirimkim00 requested changes

2023-04-11 13:49 UTC, mirimkim00 commented on lib/components/sub_pages/calendar_details/add_task/calendar_details_add_task.dart
> +                          "Start: ${start.day} ${timeService.getMonthFromNumber(start.month)} ${start.hour}:${start.minute}")),
Don't we need any hyphens between day and month?

2023-04-11 13:49 UTC, mirimkim00 commented on lib/components/sub_pages/calendar_details/add_task/calendar_details_add_task.dart
> +    description = " ";
Do you initiate it as a space?

2023-04-11 13:49 UTC, mirimkim00 commented on lib/components/sub_pages/calendar_details/add_task/calendar_details_add_task.dart
> +                          "End: ${end.day} ${timeService.getMonthFromNumber(end.month)} ${end.hour}:${end.minute}")),
Don't we need any hyphens between day and month?

2023-04-11 13:52 UTC, maciejdrobnik commented on lib/components/sub_pages/calendar_details/add_task/calendar_details_add_task.dart
> +    description = " ";
It should be empty string probably

2023-04-11 13:58 UTC, mirimkim00 requested changes

2023-04-11 13:58 UTC, mirimkim00 commented on lib/components/sub_pages/calendar_details/calendar_details_content.dart
> +                        padding: const EdgeInsets.only(right: 15),
magic number

2023-04-11 13:58 UTC, mirimkim00 commented on lib/components/sub_pages/calendar_details/calendar_details_role_check.dart
> +              return Text("Non oggi");
Is it polish?

2023-04-11 13:58 UTC, mirimkim00 commented on lib/components/sub_pages/calendar_details/calendar_details_role_check.dart
> +            return Text("Aspetta un momento perfavore");
polish again...?

2023-04-12 08:20 UTC, mirimkim00 approved these changes

2023-04-12 08:25 UTC, merged